title: My awesome site
author: mama-llama
email: mama-llama@github.com
description: > # this means to ignore newlines until "baseurl:"
  A great test page.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
